// Code generated by qtc from "index.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line index.html:1
package templates

//line index.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.html:2
type IndexPage struct { }

//line index.html:3
func (p *IndexPage) StreamName(qw422016 *qt422016.Writer) {
//line index.html:3
	qw422016.N().S(`index`)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) WriteName(qq422016 qtio422016.Writer) {
//line index.html:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.html:3
	p.StreamName(qw422016)
//line index.html:3
	qt422016.ReleaseWriter(qw422016)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) Name() string {
//line index.html:3
	qb422016 := qt422016.AcquireByteBuffer()
//line index.html:3
	p.WriteName(qb422016)
//line index.html:3
	qs422016 := string(qb422016.B)
//line index.html:3
	qt422016.ReleaseByteBuffer(qb422016)
//line index.html:3
	return qs422016
//line index.html:3
}

//line index.html:3
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line index.html:3
	qw422016.N().S(`Search IMDb`)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line index.html:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.html:3
	p.StreamTitle(qw422016)
//line index.html:3
	qt422016.ReleaseWriter(qw422016)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) Title() string {
//line index.html:3
	qb422016 := qt422016.AcquireByteBuffer()
//line index.html:3
	p.WriteTitle(qb422016)
//line index.html:3
	qs422016 := string(qb422016.B)
//line index.html:3
	qt422016.ReleaseByteBuffer(qb422016)
//line index.html:3
	return qs422016
//line index.html:3
}

//line index.html:3
func (p *IndexPage) StreamContent(qw422016 *qt422016.Writer) {
//line index.html:3
	qw422016.N().S(`<div class=jumbotron><h1 class=display-3>Search IMDb</h1><p></p><form action=/find><label for=q>Find</label> <input name=q placeholder=Something...> <button type=submit>Search!</button></form><p></p></div>`)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) WriteContent(qq422016 qtio422016.Writer) {
//line index.html:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.html:3
	p.StreamContent(qw422016)
//line index.html:3
	qt422016.ReleaseWriter(qw422016)
//line index.html:3
}

//line index.html:3
func (p *IndexPage) Content() string {
//line index.html:3
	qb422016 := qt422016.AcquireByteBuffer()
//line index.html:3
	p.WriteContent(qb422016)
//line index.html:3
	qs422016 := string(qb422016.B)
//line index.html:3
	qt422016.ReleaseByteBuffer(qb422016)
//line index.html:3
	return qs422016
//line index.html:3
}

