# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='src',
  syntax='proto3',
  serialized_options=_b('Z\035gophers.id/slides/16-grpc/src'),
  serialized_pb=_b('\n\x0csample.proto\x12\x03src\x1a\x1cgoogle/api/annotations.proto\"\x1a\n\x0b\x45\x63hoMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t2O\n\x0bUtilService\x12@\n\x04\x45\x63ho\x12\x10.src.EchoMessage\x1a\x10.src.EchoMessage\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/api/echo:\x01*B\x1fZ\x1dgophers.id/slides/16-grpc/srcb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_ECHOMESSAGE = _descriptor.Descriptor(
  name='EchoMessage',
  full_name='src.EchoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='src.EchoMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['EchoMessage'] = _ECHOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoMessage = _reflection.GeneratedProtocolMessageType('EchoMessage', (_message.Message,), dict(
  DESCRIPTOR = _ECHOMESSAGE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:src.EchoMessage)
  ))
_sym_db.RegisterMessage(EchoMessage)


DESCRIPTOR._options = None

_UTILSERVICE = _descriptor.ServiceDescriptor(
  name='UtilService',
  full_name='src.UtilService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='src.UtilService.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOMESSAGE,
    output_type=_ECHOMESSAGE,
    serialized_options=_b('\202\323\344\223\002\016\"\t/api/echo:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_UTILSERVICE)

DESCRIPTOR.services_by_name['UtilService'] = _UTILSERVICE

# @@protoc_insertion_point(module_scope)
