CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS pages (
  page_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  location TEXT NOT NULL DEFAULT '' UNIQUE,
  header BYTEA NOT NULL DEFAULT ''::BYTEA,
  body BYTEA NOT NULL DEFAULT ''::BYTEA,
  title TEXT NOT NULL DEFAULT '',
  words TEXT NOT NULL DEFAULT '',
  words_tsv TSVECTOR NOT NULL GENERATED ALWAYS AS (to_tsvector('english', words)) STORED,
  created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  refreshed TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
